# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          小葵花妈妈课堂
paginate:       5
baseurl:        ""
url:            "https://softime.github.io/unitrust"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         萝卜
  url:          https://softime.github.io/unitrust
  email:        985144332@qq.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
plugins:
  - jekyll-paginate
